# Freeze Tag Configuration
# ======================
behaviors:
  RunnerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 2.5e-4        # slightly lower for stability
      beta: 1.0e-2                # increase entropy to encourage exploration
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true             # normalize observations
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:                  # encourage exploration and interaction
        strength: 0.3
        gamma: 0.99
    max_steps: 15000000           # extend training
    time_horizon: 32              # faster feedback on wall-building/unfreezing
    summary_freq: 20000
    checkpoint_interval: 40000
    keep_checkpoints: 10

  TaggerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 2.5e-4
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:                  # encourage exploration/shooting variety
        strength: 0.3
        gamma: 0.99
    max_steps: 15000000
    time_horizon: 32              # immediate feedback on shooting actions
    summary_freq: 20000
    checkpoint_interval: 40000
    keep_checkpoints: 10
    
environment_parameters:
  lesson:
    curriculum:
      - name: Lesson1_Introduction
        completion_criteria:
          measure: reward
          behavior: TaggerBehavior
          min_lesson_length: 100
          threshold: 0.3
          require_reset: true
        value: 0.0
      - name: Lesson2_Basic
        completion_criteria:
          measure: reward
          behavior: TaggerBehavior
          min_lesson_length: 100
          threshold: 0.7
          require_reset: true
        value: 1.0
      - name: Lesson3_Intermediate
        completion_criteria:
          measure: reward
          behavior: TaggerBehavior
          min_lesson_length: 100
          threshold: 1.2
          require_reset: true
        value: 2.0
      - name: Lesson4_Advanced
        completion_criteria:
          measure: reward
          behavior: TaggerBehavior
          min_lesson_length: 100
          threshold: 1.8
          require_reset: true
        value: 3.0
      - name: Lesson5_Expert
        completion_criteria:
          measure: reward
          behavior: TaggerBehavior
          min_lesson_length: 100
          threshold: 2.5
          require_reset: true
        value: 4.0
      - name: Lesson6_Master
        value: 5.0