# Freeze Tag Configuration
# ======================
# Freeze Tag Configuration
# ======================
behaviors:
  RunnerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 20000
    checkpoint_interval: 40000
    keep_checkpoints: 250
  TaggerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 12288       # Increased for better experience diversity
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0          # Adjusted back to standard value
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 20000
    checkpoint_interval: 40000
    keep_checkpoints: 250
    
environment_parameters:
  lesson:
    curriculum:
      # Adding a simpler initial lesson for better early learning
      - name: Lesson3_Intermediate
        completion_criteria:
          measure: reward
          behavior: RunnerBehavior
          min_lesson_length: 2400
          threshold: 2.0
          require_reset: true
        value: 0.0
        
      - name: Lesson4_Advanced
        completion_criteria:
          measure: reward
          behavior: RunnerBehavior
          min_lesson_length: 800
          threshold: 2.5
          require_reset: true
        value: 1.0
        
      - name: Lesson5_Expert
        value: 2.0
        
