# Freeze Tag Configuration
# ======================

behaviors:
  RunnerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 20000
    checkpoint_interval: 40000
    keep_checkpoints: 250

  TaggerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 20000
    checkpoint_interval: 40000
    keep_checkpoints: 250
    
environment_parameters:
  lesson:
    curriculum:
      - name: Lesson1_Introduction
        completion_criteria:
          measure: reward
          behavior: RunnerBehavior
          min_lesson_length: 100
          threshold: 0.8
          require_reset: true
        value: 0.0
      - name: Lesson2_Basic
        completion_criteria:
          measure: reward
          behavior: RunnerBehavior
          min_lesson_length: 120
          threshold: 1.5
          require_reset: true
        value: 1.0
      - name: Lesson3_Intermediate
        completion_criteria:
          measure: reward
          behavior: RunnerBehavior
          min_lesson_length: 150
          threshold: 2.5
          require_reset: true
        value: 2.0
      - name: Lesson4_Advanced
        completion_criteria:
          measure: reward
          behavior: RunnerBehavior
          min_lesson_length: 200
          threshold: 3.5
          require_reset: true
        value: 3.0
      - name: Lesson5_Expert
        completion_criteria:
          measure: reward
          behavior: RunnerBehavior
          min_lesson_length: 250
          threshold: 4.5
          require_reset: true
        value: 4.0
      - name: Lesson6_Master
        value: 5.0